2024-05-14 21:18:07,069 FILE: creds.py IN: create_new_token MESSAGE: ������ ��������� iam_token: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CE54820DC0>: Failed to establish a new connection: [WinError 10051] ������� ������� ��������� �������� �� ������ ��� ����������� ����'))
2024-05-14 21:18:09,249 FILE: database.py IN: create_database MESSAGE: DATABASE: ���� ������ �������
2024-05-14 21:18:15,219 FILE: database.py IN: add_message MESSAGE: DATABASE: INSERT INTO messages VALUES (1285439190, ������, user, 0, 0, 0)
2024-05-14 21:18:15,225 FILE: creds.py IN: create_new_token MESSAGE: ������ ��������� iam_token: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CE548A68B0>: Failed to establish a new connection: [WinError 10051] ������� ������� ��������� �������� �� ������ ��� ����������� ����'))
2024-05-14 21:18:15,331 FILE: creds.py IN: create_new_token MESSAGE: ������ ��������� iam_token: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CE548AF190>: Failed to establish a new connection: [WinError 10051] ������� ������� ��������� �������� �� ������ ��� ����������� ����'))
2024-05-14 21:18:16,309 FILE: creds.py IN: create_new_token MESSAGE: ������ ��������� iam_token: HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CE548BF640>: Failed to establish a new connection: [WinError 10051] ������� ������� ��������� �������� �� ������ ��� ����������� ����'))
2024-05-14 21:18:16,431 FILE: database.py IN: add_message MESSAGE: DATABASE: INSERT INTO messages VALUES (1285439190, ������������! � ������������� ���������. ���� ������ � ����������� � ������������ ������ �� �������. ���� � ��� ���� ������, ������� ���, ����������, � ������� �������� ���������, ��� ������������� ������� /, � � ���������� ��� ������., assistant, 73, 0, 0)
